line-length = 120
indent-width = 4

target-version = "py310"

[lint]
fixable = ["ALL"]
select = ["A", "E", "F", "W", "Q", "I", "RUF", "TID"]

# E501: line too long
# E722: bare except
# E731: do not assign a lambda expression, use a def
# RUF005: consider X instead of concat
ignore = ["E501", "E722", "E731", "RUF005"]
